Repository Ameciclo/botaprarodar-web, pull requests merged in 2022-09, with the labels that each got.

#75 fix(users): Adjusting symbol for income
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/SocialInfoForm/SocialInfoForm.tsx
Labels: bug

#77 BPR 2.0.4
  .github/pull_request_template.md
  CHANGELOG.md
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.styles.ts
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.test.tsx
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.tsx
  src/modules/communities/pages/CommunitiesPages/CommunityManagementPage/CommunityManagementPage.styles.ts
  src/modules/communities/pages/CommunitiesPages/CommunityManagementPage/CommunityManagementPage.test.tsx
  src/modules/communities/pages/CommunitiesPages/CommunityManagementPage/CommunityManagementPage.tsx
  src/modules/communities/pages/CommunitiesPages/components/CommunityCard/CommunityCard.styles.ts
  src/modules/communities/pages/CommunitiesPages/components/CommunityCard/CommunityCard.tsx
  src/modules/communities/pages/CommunitiesPages/components/CommunityMenu/CommunityMenu.styles.tsx
  src/modules/communities/pages/CommunitiesPages/components/CommunityMenu/CommunityMenu.tsx
  src/modules/communities/pages/CommunitiesPages/components/CreateCommunityButton/CreateCommunityButton.styles.ts
  src/modules/communities/pages/CommunitiesPages/components/CreateCommunityButton/CreateCommunityButton.tsx
  src/modules/communities/pages/CommunityPage/CommunityPage.tsx
  src/modules/dashboard/pages/DashboardPage/components/DonutPercentageCard/DonutPercentageCard.tsx
  src/modules/dashboard/pages/DashboardPage/components/TravelTimeCard/TravelTimeCard.test.tsx
  src/modules/dashboard/pages/DashboardPage/components/TravelTimeCard/TravelTimeCard.tsx
  src/modules/dashboard/pages/DashboardPage/fragments/Dashboard/Dashboard.tsx
  src/modules/dashboard/pages/DashboardPage/fragments/MultipleCharts/MultipleCharts.tsx
  src/modules/users/models/enums/Reason.enum.ts
  src/modules/users/models/enums/index.ts
  src/modules/users/models/types/Reason.type.ts
  src/modules/users/models/types/index.ts
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.schema.ts
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.tsx
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.test.tsx
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.tsx
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/SocialInfoForm/SocialInfoForm.tsx
  src/routes/Router.test.tsx
  src/routes/routesCoordinator.ts
  src/shared/components/Menu/Menu.test.tsx
  src/shared/components/Menu/Menu.tsx
Labels: New Version

#78 feat(communities): Community Selection filtering per manager
  src/modules/communities/mocks/MockedCommunity.ts
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.test.tsx
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.tsx
Labels: enhancement

#79 BPR 2.1
  .github/workflows/dev_netlify.yml
  .github/workflows/production_netlify.yml
  CHANGELOG.md
  src/modules/communities/mocks/MockedCommunity.ts
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.test.tsx
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.tsx
Labels: New Version

#80 feat(communities): Allow admins to see all communities
  src/modules/authentication/contexts/AuthContext.tsx
  src/modules/authentication/models/AuthInterface.ts
  src/modules/authentication/services/LoginService.ts
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.test.tsx
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.tsx
  src/modules/users/services/UserService.test.ts
  src/modules/users/services/UserService.ts
Labels: enhancement

#81 BPR 2.1.1
  CHANGELOG.md
  src/modules/authentication/contexts/AuthContext.tsx
  src/modules/authentication/models/AuthInterface.ts
  src/modules/authentication/services/LoginService.ts
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.test.tsx
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.tsx
  src/modules/users/services/UserService.test.ts
  src/modules/users/services/UserService.ts
Labels: New Version

#84 refactor: Refactor validations on tests for numerical values
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.test.tsx
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/MotivationForm/MotivationForm.test.tsx
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/components/ProblemsForm/ProblemsForm.test.tsx
Labels: bug

#86 docs: Cleanup on README
  README.md
Labels: documentation

#87 docs: Cleanup on CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation

#88 docs: Removing vscode and intellij related folders from project
  .gitignore
  .idea/.gitignore
  .idea/botaprarodar-web.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/prettier.xml
  .idea/vcs.xml
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  src/modules/users/pages/LendBike/LendBikeCards/SelectBikePage.test.tsx
Labels: documentation
