Repository Ameciclo/botaprarodar-web, pull requests merged in 2022-08, with the labels that each got.

#27 refactor/utils
  package.json
  src/modules/authentication/pages/LoginPage/LoginPage.test.tsx
  src/modules/authentication/pages/LoginPage/LoginPage.tsx
  src/modules/communities/pages/CreateAndEditCommunity/components/CommunityForm/CommunityForm.test.tsx
  src/modules/communities/pages/CreateAndEditCommunity/components/CommunityForm/CommunityForm.tsx
  src/shared/components/PolarAreaChart/PolarAreaChart.tsx
  src/shared/utils/ColorsUtils.test.ts
  src/shared/utils/ColorsUtils.ts
  src/shared/utils/Dayjs.ts
  src/shared/utils/StringUtils.ts
  src/shared/utils/Toggle.ts
  src/shared/utils/index.ts
Labels: enhancement

#33 chore: Update react and types
  package.json
Labels: bug

#36 fix: Update dev_netlify
  .github/workflows/dev_netlify.yml
Labels: bug

#39 fix: Show additional option when selecting
  package-lock.json
  src/modules/users/models/types/Schooling.type.ts
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.schema.ts
  src/modules/users/pages/RegisterUser/components/RegisterUserForm/RegisterUserForm.tsx
Labels: bug

#55 fix: Fixing back buttons form communities form
  src/modules/communities/pages/CreateAndEditCommunity/CreateAndEditCommunity.test.tsx
  src/modules/communities/pages/CreateAndEditCommunity/CreateAndEditCommunity.tsx
  src/modules/communities/pages/CreateCommunityPage/CreateCommunityPage.styles.ts
  src/modules/communities/pages/CreateCommunityPage/CreateCommunityPage.test.tsx
  src/modules/communities/pages/CreateCommunityPage/CreateCommunityPage.tsx
  src/modules/communities/pages/EditCommunityPage/EditCommunityPage.styles.ts
  src/modules/communities/pages/EditCommunityPage/EditCommunityPage.test.tsx
  src/modules/communities/pages/EditCommunityPage/EditCommunityPage.tsx
  src/modules/communities/pages/EditCommunityPage/components/DeleteCommunityButton/DeleteCommunityButton.styles.ts
  src/modules/communities/pages/EditCommunityPage/components/DeleteCommunityButton/DeleteCommunityButton.tsx
  src/modules/communities/pages/components/CommunityForm/CommunityForm.styles.ts
  src/modules/communities/pages/components/CommunityForm/CommunityForm.test.tsx
  src/modules/communities/pages/components/CommunityForm/CommunityForm.tsx
  src/modules/communities/services/CommunityService.ts
  src/routes/routesCoordinator.ts
Labels: bug, fix

#59 fix: Removing delete button from Editing community
  src/modules/communities/pages/EditCommunityPage/EditCommunityPage.test.tsx
  src/modules/communities/pages/EditCommunityPage/EditCommunityPage.tsx
Labels: bug, fix

#60 refactor: Making component names consistent
  src/modules/communities/pages/CommunityPage/components/CreateCommunityButton/CreateCommunityButton.tsx
Labels: fix

#61 BPR 2.0.3
  CHANGELOG.md
  src/modules/communities/pages/CommunityPage/components/CreateCommunityButton/CreateCommunityButton.tsx
  src/modules/communities/pages/EditCommunityPage/EditCommunityPage.test.tsx
  src/modules/communities/pages/EditCommunityPage/EditCommunityPage.tsx
Labels: New Version

#65 feat(dashboard): Switching display minutes to hours on the dashboard
  src/modules/dashboard/pages/DashboardPage/components/TravelTimeCard/TravelTimeCard.test.tsx
  src/modules/dashboard/pages/DashboardPage/components/TravelTimeCard/TravelTimeCard.tsx
Labels: enhancement

#71 docs: PROD PR Template
  .github/pull_request_template.md
Labels: documentation

#72 refactor(communities): Making community display page only for selection
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.styles.ts
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.test.tsx
  src/modules/communities/pages/CommunitiesPages/CommunitiesSelectionPage/CommunitiesSelectionPage.tsx
  src/modules/communities/pages/CommunitiesPages/CommunityManagementPage/CommunityManagementPage.styles.ts
  src/modules/communities/pages/CommunitiesPages/CommunityManagementPage/CommunityManagementPage.test.tsx
  src/modules/communities/pages/CommunitiesPages/CommunityManagementPage/CommunityManagementPage.tsx
  src/modules/communities/pages/CommunitiesPages/components/CommunityCard/CommunityCard.styles.ts
  src/modules/communities/pages/CommunitiesPages/components/CommunityCard/CommunityCard.tsx
  src/modules/communities/pages/CommunitiesPages/components/CommunityMenu/CommunityMenu.styles.tsx
  src/modules/communities/pages/CommunitiesPages/components/CommunityMenu/CommunityMenu.tsx
  src/modules/communities/pages/CommunitiesPages/components/CreateCommunityButton/CreateCommunityButton.styles.ts
  src/modules/communities/pages/CommunitiesPages/components/CreateCommunityButton/CreateCommunityButton.tsx
  src/modules/communities/pages/CommunityPage/CommunityPage.tsx
  src/routes/Router.test.tsx
  src/routes/routesCoordinator.ts
Labels: enhancement

#73 feat: Changing UI display to show <1% when data is irrelevant
  src/modules/dashboard/pages/DashboardPage/components/DonutPercentageCard/DonutPercentageCard.tsx
Labels: enhancement
